#!/bin/bash
# check_snmp_synology for nagios version 1.1
# 30.04.2013  Nicolas Ordonez, Switzerland
#---------------------------------------------------
# this plugin check the health of your Synology NAS
# - System status (Power, Fans)
# - Disks status 
# - RAID status
#
# Tested with DSM 4.2
#---------------------------------------------------
# Based on http://download.synology.com/download/ds/userguide/Synology_DiskStation_MIB_Guide_enu_20110725.pdf
#---------------------------------------------------

SNMPCOMMUNITY="public"
SNMPVERSION="2c"
SNMPWALK="/usr/bin/snmpwalk"
SNMPGET="/usr/bin/snmpget"

HOSTNAME=""
option_found=0
healthStatus=0
healthString=""
verbose="no"

#OID declarations
OID_syno="1.3.6.1.4.1.6574"
OID_model="1.3.6.1.4.1.6574.1.5.1.0"
OID_serialNumber="1.3.6.1.4.1.6574.1.5.2.0"
OID_DSMVersion="1.3.6.1.4.1.6574.1.5.3.0"
OID_systemStatus="1.3.6.1.4.1.6574.1.1.0"
OID_powerStatus="1.3.6.1.4.1.6574.1.3.0"
OID_systemFanStatus="1.3.6.1.4.1.6574.1.4.1.0"
OID_CPUFanStatus="1.3.6.1.4.1.6574.1.4.2.0"
OID_temp="1.3.6.1.4.1.6574.1.2.0"

OID_disk=""
OID_diskID="1.3.6.1.4.1.6574.2.1.1.2"
OID_diskModel="1.3.6.1.4.1.6574.2.1.1.3"
OID_diskStatus="1.3.6.1.4.1.6574.2.1.1.5"
OID_diskTemp="1.3.6.1.4.1.6574.2.1.1.6"
OID_diskSize="1.3.6.1.4.1.6574.3.1.1.4"        # Taille totale du volume en Ko
OID_diskUsed="1.3.6.1.4.1.6574.3.1.1.5"        # Espace utilisé en Ko
OID_diskFree="1.3.6.1.4.1.6574.3.1.1.6"        # Espace libre en Ko
OID_diskPercent="1.3.6.1.4.1.6574.3.1.1.7"     # Pourcentage utilisé

OID_RAID=""
OID_RAIDName="1.3.6.1.4.1.6574.3.1.1.2"
OID_RAIDStatus="1.3.6.1.4.1.6574.3.1.1.3"
usage()
{
        echo "usage: ./check_snmp_synology -h hostname [-v verbose]"
        echo ""
        exit 3
}


while getopts h:v OPTNAME; do
        case "$OPTNAME" in
        h)
                HOSTNAME="$OPTARG"
                option_found=1
                ;;

        v)
		verbose="yes"
		;;
        *)
                usage
                ;;
        esac
done

if [ "$option_found" = "0" ] || [ "$HOSTNAME" = "" ] ; then
    usage
else
    nbDisk=`$SNMPWALK -OQne -t 10 -v $SNMPVERSION -c $SNMPCOMMUNITY $HOSTNAME 1.3.6.1.4.1.6574.2.1.1.2 2> /dev/null | wc -l `
    nbRAID=`$SNMPWALK -OQne -t 10 -v $SNMPVERSION -c $SNMPCOMMUNITY $HOSTNAME 1.3.6.1.4.1.6574.3.1.1.2 2> /dev/null | wc -l`

    for i in `seq 1 $nbDisk`;
    do
      OID_disk="$OID_disk $OID_diskID.$(($i-1)) $OID_diskModel.$(($i-1)) $OID_diskStatus.$(($i-1)) $OID_diskTemp.$(($i-1)) " 
    done
    for i in `seq 1 $nbRAID`;
    do
      OID_RAID="$OID_RAID $OID_RAIDName.$(($i-1)) $OID_RAIDStatus.$(($i-1))" 
    done

    syno=`$SNMPGET -OQne -t 10 -v $SNMPVERSION -c $SNMPCOMMUNITY $HOSTNAME $OID_model $OID_serialNumber $OID_DSMVersion $OID_systemStatus $OID_powerStatus $OID_systemFanStatus $OID_CPUFanStatus $OID_temp $OID_disk $OID_RAID 2> /dev/null`

    if [ "$?" != "0" ] ; then
        echo "CRITICAL - Problem with SNMP request"
        exit 2
    fi 

    model=$(echo "$syno" | grep $OID_model | cut -d "=" -f2)
    if [ "$verbose" = "yes" ] ; then    echo "Synology model:   $model" ; fi

    serialNumber=$(echo "$syno" | grep $OID_serialNumber | cut -d "=" -f2)
    if [ "$verbose" = "yes" ] ; then    echo "Synology s/n:     $serialNumber" ; fi

    DSMVersion=$(echo "$syno" | grep $OID_DSMVersion | cut -d "=" -f2)
    if [ "$verbose" = "yes" ] ; then    echo "DSM Version:      $DSMVersion" ; fi

    healthString="Synology $model (s/n:$serialNumber, $DSMVersion)"


    RAIDName=$(echo "$syno" | grep $OID_RAIDName | cut -d "=" -f2)
    RAIDStatus=$(echo "$syno" | grep $OID_RAIDStatus | cut -d "=" -f2 | sed 's/^[ \t]*//;s/[ \t]*$//')


    #Check system status
    systemStatus=$(echo "$syno" | grep $OID_systemStatus | cut -d "=" -f2 | sed 's/^[ \t]*//;s/[ \t]*$//')

    if [ "$systemStatus" != "1" ] ; then
       if [ "$systemStatus" = "2" ] ; then	systemStatus="Failed";		fi
       healthStatus=2
       healthString="$healthString, System status: $systemStatus "
    else
	systemStatus="Normal"
    fi
    if [ "$verbose" = "yes" ] ; then    echo "System Status:     $systemStatus" ; fi


    #Check power status
    powerStatus=$(echo "$syno" | grep $OID_powerStatus | cut -d "=" -f2 | sed 's/^[ \t]*//;s/[ \t]*$//')

    if [ "$powerStatus" != "1" ] ; then
       if [ "$powerStatus" = "2" ] ; then	powerStatus="Failed";		fi
       healthStatus=2
       healthString="$healthString, Power status: $powerStatus "
    else
        powerStatus="Normal"
    fi
    if [ "$verbose" = "yes" ] ; then    echo "Power Status:      $powerStatus" ; fi

    #Check system fan status
    systemFanStatus=$(echo "$syno" | grep $OID_systemFanStatus | cut -d "=" -f2 | sed 's/^[ \t]*//;s/[ \t]*$//')
    if [ "$systemFanStatus" != "1" ] ; then
       if [ "$systemFanStatus" = "2" ] ; then	systemFanStatus="Failed";		fi
       healthStatus=2
       healthString="$healthString, System fan status: $systemFanStatus "
    else
        systemFanStatus="Normal"
    fi
    if [ "$verbose" = "yes" ] ; then    echo "System Fan Status: $systemFanStatus" ; fi

    #Check CPU fan status
    CPUFanStatus=$(echo "$syno" | grep $OID_CPUFanStatus | cut -d "=" -f2 | sed 's/^[ \t]*//;s/[ \t]*$//')
    if [ "$CPUFanStatus" != "1" ] ; then
       if [ "$CPUFanStatus" = "2" ] ; then	CPUFanStatus="Failed";		fi
       healthStatus=2
       healthString="$healthString, CPU fan status: $CPUFanStatus "
    else
	CPUFanStatus="Normal"
    fi
    if [ "$verbose" = "yes" ] ; then    echo "CPU Fan Status:    $CPUFanStatus" ; fi

    #Check all disk status
    if [ "$verbose" = "yes" ] ; then	echo "Number of disks:   $nbDisk" ; fi
    for i in `seq 1 $nbDisk`;
    do
    	diskID[$i]=$(echo "$syno" | grep $OID_diskID.$(($i-1)) | cut -d "=" -f2)
    	diskModel[$i]=$(echo "$syno" | grep $OID_diskModel.$(($i-1)) | cut -d "=" -f2)
    	diskStatus[$i]=$(echo "$syno" | grep $OID_diskStatus.$(($i-1)) | cut -d "=" -f2 | sed 's/^[ \t]*//;s/[ \t]*$//')
    	diskTemp[$i]=$(echo "$syno" | grep $OID_diskTemp.$(($i-1)) | cut -d "=" -f2 | sed 's/^[ \t]*//;s/[ \t]*$//')

	if [ "${diskStatus[$i]}" != "1" ] ; then
       	   if [ "${diskStatus[$i]}" = "2" ] ; then	diskStatus[$i]="Initialized";			fi
	   if [ "${diskStatus[$i]}" = "3" ] ; then	diskStatus[$i]="NotInitialized";		fi
	   if [ "${diskStatus[$i]}" = "4" ] ; then	diskStatus[$i]="SystemPartitionFailed";		fi
	   if [ "${diskStatus[$i]}" = "5" ] ; then	diskStatus[$i]="Crashed";			fi
           healthStatus=2
           healthString="$healthString, problem with ${diskID[$i]} (model:${diskModel[$i]}) status:${diskStatus[$i]} temperature:${diskTemp[$i]} C "
	else
	    diskStatus[$i]="Normal"
        fi
        if [ "$verbose" = "yes" ] ; then    echo "${diskID[$i]} (model:${diskModel[$i]}) status:${diskStatus[$i]} temperature:${diskTemp[$i]} C" ; fi
    done

    #Check all RAID volume status
    if [ "$verbose" = "yes" ] ; then	echo "Number of RAID volume: $nbRAID" ; fi
    for i in `seq 1 $nbRAID`;
    do
	RAIDName[$i]=$(echo "$syno" | grep $OID_RAIDName.$(($i-1)) | cut -d "=" -f2)
	RAIDStatus[$i]=$(echo "$syno" | grep $OID_RAIDStatus.$(($i-1)) | cut -d "=" -f2 | sed 's/^[ \t]*//;s/[ \t]*$//')

        if [ "${RAIDStatus[$i]}" != "1" ] ; then
       	   if [ "${RAIDStatus[$i]}" = "2" ] ; then	RAIDStatus[$i]="Repairing";			fi
           if [ "${RAIDStatus[$i]}" = "3" ] ; then	RAIDStatus[$i]="Migrating";			fi
           if [ "${RAIDStatus[$i]}" = "4" ] ; then	RAIDStatus[$i]="Expanding";			fi
           if [ "${RAIDStatus[$i]}" = "5" ] ; then	RAIDStatus[$i]="Deleting";			fi
           if [ "${RAIDStatus[$i]}" = "6" ] ; then	RAIDStatus[$i]="Creating";			fi
           if [ "${RAIDStatus[$i]}" = "7" ] ; then	RAIDStatus[$i]="RaidSyncing";			fi
           if [ "${RAIDStatus[$i]}" = "8" ] ; then	RAIDStatus[$i]="RaidParityChecking";		fi
           if [ "${RAIDStatus[$i]}" = "9" ] ; then	RAIDStatus[$i]="RaidAssembling";		fi
           if [ "${RAIDStatus[$i]}" = "10" ] ; then	RAIDStatus[$i]="Canceling";			fi
           if [ "${RAIDStatus[$i]}" = "11" ] ; then	RAIDStatus[$i]="Degrade";			fi
           if [ "${RAIDStatus[$i]}" = "12" ] ; then	RAIDStatus[$i]="Crashed";			fi
    
           healthStatus=2
           healthString="$healthString, RAID status ($RAIDName ): $RAIDStatus "
	else
	    RAIDStatus[$i]="Normal"
	fi
        if [ "$verbose" = "yes" ] ; then    echo "${RAIDName[$i]} status:${RAIDStatus[$i]}" ; fi
    done

    if [ "$healthStatus" = "0" ] ; then
	echo "OK - $healthString is in good health"
        exit 0
    else
	echo "CRITICAL - $healthString"
	exit 2
    fi
fi
